import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className="bg-gray-400 p-5 flex gap-5">
      <Link href="/">Home</Link>
      <Link href="/about">About</Link>
      <Link href="/about/team">Team</Link>
      <Link href="/services">Services</Link></header>
              
       {children}

       <footer className="bg-slate-300 p-5 flex justify-center items-center">
      <span className="mr-2"></span>
      
      {/* Contact Link with Hover Effect */}
      <Link href="/about/contacts" className="relative group">
        <span className="group-hover:text-blue-500 transition duration-300">Contacts Details</span>
      </Link>
    </footer>
      </body>
    </html>
  );
}
